  alias: Send air quality alert when window opend
  trigger:
    - platform: state
      # Balcony door
      entity_id: binary_sensor.door_window_sensor_balcony
      to: 'on'
    - platform: state
      # Kitchen window
      entity_id: binary_sensor.door_window_sensor_kitchen
      to: 'on'
    - platform: state
      # Living room window
      entity_id: binary_sensor.door_window_sensor_living_room
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ states.sensor.airly_pm25.state | float > states.sensor.pm25_max_level.state | float }}'
      - condition: template
        value_template: '{{ states.sensor.airly_pm10.state | float > states.sensor.pm10_max_level.state | float }}'
  action:
    - service: notify.defaultPushOver
      data:
        message: 'Wietrzenie nie jest dobrym pomysłem.

        PM 2.5 
        
          Zewnątrz: {{ states.sensor.airly_pm25.state }} μg/m3 - ({{ (states.sensor.airly_pm25.state | float / states.sensor.pm25_max_level.state | float * 100) | round(0) }}%)
        
          Wewnątrz: {{ states.sensor.air_quality_indoor_pm25.state }} μg/m3 - ({{ (states.sensor.air_quality_indoor_pm25.state | float / states.sensor.pm25_max_level.state | float * 100) | round(0) }}%)

        PM 10
        
          Zewnątrz: {{ states.sensor.airly_pm10.state }} μg/m3 - ({{ (states.sensor.airly_pm10.state | float / states.sensor.pm10_max_level.state | float * 100) | round(0) }}%)
        
          Wewnątrz: {{ states.sensor.air_quality_indoor_pm10.state }} μg/m3 - ({{ (states.sensor.air_quality_indoor_pm10.state | float / states.sensor.pm10_max_level.state | float * 100) | round(0) }}%)'